src/Entity/Vol.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VolRepository")
 */
class Vol
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateDepart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateArrivee;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $VilleDepart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $VilleArrivee;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gestionnaire", inversedBy="vols")
     */
    private $gestionnaire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Avion", inversedBy="vols")
     */
    private $avion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pilote", inversedBy="vols")
     */
    private $pilote;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Passager", inversedBy="vols")
     */
    private $passager;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Passager", mappedBy="vols")
     */
    private $passagers;

    public function __construct()
    {
        $this->passagers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->DateDepart;
    }

    public function setDateDepart(\DateTimeInterface $DateDepart): self
    {
        $this->DateDepart = $DateDepart;

        return $this;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->DateArrivee;
    }

    public function setDateArrivee(\DateTimeInterface $DateArrivee): self
    {
        $this->DateArrivee = $DateArrivee;

        return $this;
    }

    public function getVilleDepart(): ?string
    {
        return $this->VilleDepart;
    }

    public function setVilleDepart(string $VilleDepart): self
    {
        $this->VilleDepart = $VilleDepart;

        return $this;
    }

    public function getVilleArrivee(): ?string
    {
        return $this->VilleArrivee;
    }

    public function setVilleArrivee(string $VilleArrivee): self
    {
        $this->VilleArrivee = $VilleArrivee;

        return $this;
    }

    public function getGestionnaire(): ?gestionnaire
    {
        return $this->gestionnaire;
    }

    public function setGestionnaire(?gestionnaire $gestionnaire): self
    {
        $this->gestionnaire = $gestionnaire;

        return $this;
    }

    public function getAvion(): ?Avion
    {
        return $this->avion;
    }

    public function setAvion(?Avion $avion): self
    {
        $this->avion = $avion;

        return $this;
    }

    public function getPilote(): ?Pilote
    {
        return $this->pilote;
    }

    public function setPilote(?Pilote $pilote): self
    {
        $this->pilote = $pilote;

        return $this;
    }

    public function getPassager(): ?Passager
    {
        return $this->passager;
    }

    public function setPassager(?Passager $passager): self
    {
        $this->passager = $passager;

        return $this;
    }

    /**
     * @return Collection|Passager[]
     */
    public function getPassagers(): Collection
    {
        return $this->passagers;
    }

    public function addPassager(Passager $passager): self
    {
        if (!$this->passagers->contains($passager)) {
            $this->passagers[] = $passager;
            $passager->addVol($this);
        }

        return $this;
    }

    /**
     * @param Passager $passager
     * @return Vol
     */
    public function removePassager(Passager $passager): self
    {
        if ($this->passagers->contains($passager)) {
            $this->passagers->removeElement($passager);
            $passager->removeVol($this);
        }

        return $this;
    }
}

src/Form/VolType.php
<?php

namespace App\Form;

use App\Entity\Vol;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('DateDepart')
            ->add('DateArrivee')
            ->add('VilleDepart')
            ->add('VilleArrivee')
            ->add('gestionnaire')
            ->add('avion')
            ->add('pilote')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vol::class,
        ]);
    }
}

src/Controller/VolController.php
<?php

namespace App\Controller;


use App\Entity\Passager;
use App\Entity\Pilote;
use App\Entity\Avion;
use App\Entity\Vol;
use App\Form\VolType;
use App\Repository\VolRepository;
use App\Repository\PassagerRepository;
use App\Repository\PiloteRepository;
use App\Repository\AvionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vol")
 */
class VolController extends AbstractController
{
    /**
     * @Route("/", name="vol_index", methods={"GET"})
     * @param VolRepository $volRepository
     * @return Response
     */
    public function index(VolRepository $volRepository): Response
    {
        return $this->render('vol/index.html.twig', [
            'vols' => $volRepository->findAll(),
        ]);
    }
    /**
     * Cette fonction nous permet d'afficher la liste des vols que
     * le gestionnaire à pu créer, qui sont réservable.
     */

    /**
     * @Route("/indexPassager", name="vol_indexpassager", methods={"GET"})
     * @param VolRepository $volRepository
     * @return Response
     */
    public function indexPassager(VolRepository $volRepository): Response
    {
        $passager = $this->getUser()->getPassager();
        return $this->render('vol/indexPassager.html.twig', [
            'vols' => $volRepository->findAll(),
            'passagerVols' => $passager->getVols()
        ]);
    }

    /**
     *Cette fonction affecte le passager à un vol tout en lui affichant un message de confirmation de Vol
     */

    /**
     * @Route("/indexPassagerConfirm/{id}", name="vol_indexPassagerConfirm", methods={"GET"})
     * @param Vol $vol
     * @param PassagerRepository $passagerRepository
     * @param VolRepository $volRepository
     * @return Response
     */
    public function affectationPassager(Vol $vol, PassagerRepository $passagerRepository, VolRepository $volRepository): Response
    {
        $passager = $passagerRepository->find($this->getUser()->getPassager()->getId());
        $entityManager = $this->getDoctrine()->getManager();
        $vol->addPassager($passager);
        $entityManager->persist($vol);
        $entityManager->flush();
        return $this->render('vol/indexPassagerConfirm.html.twig', [
            'vols' => $volRepository->findAll(),
        ]);
    }
    /**
     * Cette fonction affiche tous les vols du passager
     */

    /**
     * @Route("/listingvolPassager", name="vol_listingvolPassager", methods={"GET"})
     * @return Response
     */
    public function listingvolPassager():Response
    {
        $em = $this->getDoctrine()->getManager();
        $passager = $em->getRepository(Passager::class)->find($this->getUser()->getPassager()->getId());
        return $this->render('vol/listingvolPassager.html.twig',[
            'passager' => $passager
        ]);

    }

    /**
     * Cette fonction affiche tous les vols d'un pilote
     */

    /**
     * @Route("/listingvolPilote", name="vol_listingvolPilote", methods={"GET"})
     * @return Response
     */
    public function listingvolPilote():Response
    {
        $em = $this->getDoctrine()->getManager();
        $pilote = $em->getRepository(Pilote::class)->find($this->getUser()->getPilote()->getId());
        return $this->render('vol/listingvolPilote.html.twig',[
            'pilote' => $pilote
        ]);
    }

    /**
     * Cette fonction affiche tous les vols de départ, pour un responsable, pour avoir un oeil sur
     * son Aéroport.
     */

    /**
     * @Route("/listingvoldepartResponsable", name="vol_listingvoldepartResponsable", methods={"GET"})
     * @return Response
     */
    public function listingvoldepartResponsable():Response
    {
        $em = $this->getDoctrine()->getManager();
        $vols = $em->getRepository(Vol::class)->findAll();
        return $this->render('vol/listingvoldepartResponsable.html.twig',[
            'vols' => $vols
        ]);
    }

    /**
     * Cette fonction affiche tous les Avions pour le responsable
     */

    /**
     * @Route("/listingvolAvion", name="vol_listingvolAvion", methods={"GET"})
     * @return Response
     */
    public function listingvolAvion():Response
    {
        $em = $this->getDoctrine()->getManager();
        $avions = $em->getRepository(Avion::class)->findAll();
        return $this->render('vol/listingvolAvion.html.twig',[
            'avions' => $avions
        ]);
    }
    /**
     * Cette fonction affiche tous les vols par avion, pour le responsable
     */
    /**
     * @Route("/listingVolparavion", name="vol_listingVolparavion", methods={"GET"})
     * @return Response
     */
    public function listingVolparavion(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $avion = $em->getRepository(Avion::class)->find(1);
        return $this->render('vol/listingVolparavion.html.twig', [
            'avion' => $avion,
        ]);
    }

    /**
     * Cette fonction permet la création d'un nouveau vol, pour le gestionnaire.
     * Le pilote et l'avion sont affecté en même temps
     */
    /**
     * @Route("/ajout", name="vol_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $vol = new Vol();
        $form = $this->createForm(VolType::class, $vol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vol);
            $entityManager->flush();

            return $this->redirectToRoute('vol_index');
        }

        return $this->render('vol/new.html.twig', [
            'vol' => $vol,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vol_show", methods={"GET"})
     * @param Vol $vol
     * @return Response
     */
    public function show(Vol $vol): Response
    {
        return $this->render('vol/show.html.twig', [
            'vol' => $vol,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="vol_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Vol $vol
     * @return Response
     */
    public function edit(Request $request, Vol $vol): Response
    {
        $form = $this->createForm(VolType::class, $vol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vol_index', [
                'id' => $vol->getId(),
            ]);
        }

        return $this->render('vol/edit.html.twig', [
            'vol' => $vol,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vol_delete", methods={"DELETE"})
     * @param Request $request
     * @param Vol $vol
     * @return Response
     */
    public function delete(Request $request, Vol $vol): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vol->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($vol);
            $entityManager->flush();
        }

        return $this->redirectToRoute('vol_index');
    }

}

templates/vol/_delete_form.html.twig
<form method="post" action="{{ path('vol_delete', {'id': vol.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vol.id) }}">
    <button class="btn btn-primary btn-xs">Effacer</button>
</form>

templates/vol/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-xs">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/vol/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Vol{% endblock %}

{% block body %}
    <h1>Modifier un vol</h1>

    {{ include('vol/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('vol_index') }}">retour</a>

    {{ include('vol/_delete_form.html.twig') }}
{% endblock %}

templates/vol/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vol index{% endblock %}

{% block body %}
    <h1>Vol index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>DateDepart</th>
                <th>DateArrivee</th>
                <th>VilleDepart</th>
                <th>VilleArrivee</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vol in vols %}
            <tr>
                <td>{{ vol.id }}</td>
                <td>{{ vol.DateDepart ? vol.DateDepart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ vol.DateArrivee ? vol.DateArrivee|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ vol.VilleDepart }}</td>
                <td>{{ vol.VilleArrivee }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="{{ path('vol_show', {'id': vol.id}) }}">Voir</a>
                    <a class="btn btn-primary btn-xs" href="{{ path('vol_edit', {'id': vol.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('vol_new') }}">Nouveau vol</a>
{% endblock %}

templates/vol/indexPassager.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vol index{% endblock %}

{% block body %}
    <h1>Vol index</h1>
    <div class="table-responsive">
        <table>
            <thead>
            <tr>
                <th>Id</th>
                <th>DateDepart</th>
                <th>DateArrivee</th>
                <th>VilleDepart</th>
                <th>VilleArrivee</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% set showVol = 'yes' %}
            {% set horaireConflit = 'no' %}
            {% set capaciteAtteint = 'no' %}
            {% for vol in vols %}
                <tr>
                    <td>{{ vol.id }}</td>
                    <td>{{ vol.DateDepart ? vol.DateDepart|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ vol.DateArrivee ? vol.DateArrivee|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ vol.VilleDepart }}</td>
                    <td>{{ vol.VilleArrivee }}</td>
                    <td>
                        <!---Ici nous récupérons tous les vols qui se trouve en base de données, on compare
               chaque vol en base de donnée qu'à déjà réserver le client, si on voit que le client
               à prit un vol durant la même plage horaire, alors on lui affiche un message personnalisé. On compare
               également le nombre de passager à la capacité totale d'un avion.-->

                        {% if passagerVols is not empty %}
                            {% for passagerVol in passagerVols %}
                                {% if vol.DateDepart <= passagerVol.DateArrivee and vol.DateArrivee >= passagerVol.DateDepart %}
                                    {% set horaireConflit = 'yes' %}
                                    {% set showVol = 'no' %}
                                {% endif %}
                                {% if vol.passagers|length >= vol.avion.capacite %}
                                    {% set capaciteAtteint = 'yes' %}
                                    {% set showVol = 'no' %}
                                {% endif %}

                                {% if horaireConflit == 'yes' %}
                                    Conflit horaire avec un autre vol
                                {% elseif capaciteAtteint == 'yes' %}
                                    La capacité de ce vol est atteinte
                                {% elseif showVol != 'no'%}
                                    <a class ="btn btn-primary btn-xs" href="{{ path('vol_indexPassagerConfirm', {id: vol.id}) }}">Reserver </a>
                                {% endif %}

                            {% endfor %}
                        {% elseif vol.passagers|length >= vol.avion.capacite %}
                            La capacité de ce vol est atteinte
                        {% else %}
                            <a class ="btn btn-primary btn-xs" href="{{ path('vol_indexPassagerConfirm', {id: vol.id}) }}">Reserver </a>
                        {% endif %}
                        {% set showVol = 'yes' %}

                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Aucun enregistrement trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/vol/indexPassagerConfirm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Demande de Reservation OK</h1>
    <a href= "{{ path('office_passager') }}">Retour</a>
{% endblock %}

templates/vol/listingVolparavion.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% for vol in avion.vols %}
    {{ vol.VilleDepart }}
    {{ vol.VilleArrivee }}
{% endfor %}
{% endblock %}

templates/vol/listingvolAvion.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% for avion in avions %}
    {{ avion.modele }}
    <a class ="btn btn-primary btn-xs" href="{{ path('vol_listingVolparavion', {avion: avion.id}) }}">Voir tous les vols </a>
{% endfor %}
{% endblock %}

templates/vol/listingvolPassager.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="container">
    {% for vol in passager.vols %}
        <div>
        <p>
            {{ vol.villeArrivee }}
        </p>
        </div>
    {% endfor %}
    <a href= "{{ path('office_passager') }}">Retour</a>
</div>
 {% endblock %}

templates/vol/listingvolPilote.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% for vol in pilote.vols %}
    {{ vol.villeArrivee }}
{% endfor %}
{% endblock %}

templates/vol/listingvoldepartResponsable.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% for vol in vols %}
    {{ vol.villeDepart }}

{% endfor %}
{% endblock %}

templates/vol/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau vol{% endblock %}

{% block body %}
    <h1>Cree un nouveau Vol</h1>

    {{ include('vol/_form.html.twig') }}

    <a href="{{ path('vol_index') }}">Retour</a>
{% endblock %}

templates/vol/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vol{% endblock %}

{% block body %}
    <h1>Vol</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vol.id }}</td>
            </tr>
            <tr>
                <th>DateDepart</th>
                <td>{{ vol.DateDepart ? vol.DateDepart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateArrivee</th>
                <td>{{ vol.DateArrivee ? vol.DateArrivee|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>VilleDepart</th>
                <td>{{ vol.VilleDepart }}</td>
            </tr>
            <tr>
                <th>VilleArrivee</th>
                <td>{{ vol.VilleArrivee }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn-default" href="{{ path('vol_index') }}">Retour</a>

    <a class="btn-default" href="{{ path('vol_edit', {'id': vol.id}) }}">Modifier</a>

    {{ include('vol/_delete_form.html.twig') }}
{% endblock %}